### ISSUE TITLE
PowerShell 7 breaks some of the commands because of Get-WmiObject

### ISSUE THREAD

**Issue by wordeater** [Purp1eW0lf/Blue-Team-Notes#4]
Instead of `Get-WmiObject`, you can just use `Get-CimInstance` in most cases, maybe all cases.

**Comment by Purp1eW0lf** [comment]
100% on my to do list

I reference in the notes 

<img width="952" alt="image" src="https://user-images.githubusercontent.com/44196051/209127245-abb42395-5a9f-4766-b7f0-86170e8a7153.png">
